PORTFOLIO_NUMBER = "Portfolio or identifier (e.g. Depot, Portfolio, VV-Portfolio)."
TRANSACTION_TYPE = "Original transaction type label from the document."
STANDARDIZED_TRANSACTION_TYPE = "Normalized transaction type."
TRANSACTION_DESCRIPTION = "Raw transaction description, usually instrument-related."
TRADE_DATE = "Execution or order date."
BOOK_DATE = "Accounting or booking date."
VALUE_DATE = "Settlement or Valuta date."
EX_DATE = "Ex-date for dividends or interest only."
REFERENCE = "Bank reference or order number."
MOVEMENTS = "Actual financial flows for the transaction, such as security and cash movements."
SUBJECT_INSTRUMENT = "Context instrument used only when the instrument does not itself move, such as dividends or coupons."

INSTRUMENT_TYPE = "Type of instrument."
INSTRUMENT_NAME = "Human-readable instrument or account name from the document."
QUOTE_TYPE = "Piece = per unit; Percentage = nominal-based pricing for bonds."
INSTRUMENT_REFERENCES = "Visible identifiers such as ISIN, Valor, WKN, IBAN, or account number."

REFERENCE_KEY = "Reference key identifying the kind of identifier."
REFERENCE_VALUE = "Reference value exactly as shown in the document."

NET_QUANTITY = "Signed quantity from portfolio perspective, positive for inflow and negative for outflow."
PRICE = "Explicitly stated price only. Never calculate missing prices."
PRICE_CURRENCY = "Currency of the price, present only when price is explicit."
AMOUNTS = "Cash-side breakdown lines such as gross amount, fees, taxes, and accrued interest."

AMOUNT_DESCRIPTION = "Exact description from the document for this cash breakdown line."
AMOUNT_STANDARDIZED_CODE = "Normalized type for the cash breakdown component."
AMOUNT_QUANTITY = "Signed monetary value from portfolio perspective."
AMOUNT_CURRENCY = "Currency of the breakdown amount."
